### ISSUE TITLE
"Close Tab at logout" SSH option

### ISSUE THREAD

**Issue by eugenov** [kingToolbox/WindTerm#210] opened 2021-09-29 08:16 UTC
Hello!
Can I set somewhere "Close Tab at ssh logout": true? Just for session, or WindTerm-wide? It's an option that helps to not use mouse when it's not necessarily.
Thank you.

**Comment by kingToolbox** [comment] 2021-09-29 08:41
Sorry, there is currently no such setting, and I also recommend not to do so. Because WindTerm cannot distinguish whether the disconnection is caused by `logout` or other reasons. If the tab is closed as soon as the disconnection is detected, then sometimes important displayed content is also lost. 

You can use the shortcut key `Ctrl+Shift+W` to quickly close tabs without using the mouse.

**Comment by eugenov** [comment] 2021-09-29 10:15
Ok, what about "Close Tab at broken session", when tab name becomes red?

**Comment by kingToolbox** [comment] 2021-10-01 14:22
It is not difficult to implement this feature, but terminals should not actively perform too many operations, especially the close/shutdown operation. If there is no log, `close session` means that all output is lost. Obviously sometimes it will cause trouble to users. 

Although using the shortcut key or the close button is a bit more troublesome, it is obviously more secure. So this issue will be closed, thank you.

**Closed by kingToolbox** 2021-10-01 14:22 UTC
