### ISSUE TITLE
2FA and ssh keyfile

### ISSUE THREAD

**Issue by R60olus** [kingToolbox/WindTerm#63] opened 2021-03-16 07:40 UTC
It's not possible to login to a server with 2FA and ssh keyfile.
System:
Edition: Windows 10 Enterprise LTSC 64bit

Recreate the issue:
1. open windterm
2. create new session
3. enter username
4. select key-file
5. ERROR "Partial success for 'publickey'. Authentication that can continue: keyboard-interactive"

The main problem is, there are no other tabs like "keyboard-interactive". There is only the Tab to select the keyfile.

Log:
```
[2021-03-16 08:27:36] ssh_packet_userauth_failure: Access denied for 'none'. Authentication that can continue: publickey
[2021-03-16 08:27:36] ssh_packet_userauth_failure: Access denied for 'none'. Authentication that can continue: publickey
[2021-03-16 08:27:43] ssh_pki_import_privkey_base64: Trying to decode privkey passphrase=false
[2021-03-16 08:27:43] ssh_pki_openssh_import: Opening OpenSSH private key: ciphername: none, kdf: none, nkeys: 1
[2021-03-16 08:27:43] ssh_key_algorithm_allowed: Checking rsa-sha2-512 with list <ssh-ed25519-cert-v01@openssh.com,ecdsa-sha2-nistp521-cert-v01@openssh.com,ecdsa-sha2-nistp384-cert-v01@openssh.com,ecdsa-sha2-nistp256-cert-v01@openssh.com,rsa-sha2-512-cert-v01@openssh.com,rsa-sha2-256-cert-v01@openssh.com,ssh-rsa-cert-v01@openssh.com,ssh-dss-cert-v01@openssh.com,ssh-ed25519,ecdsa-sha2-nistp521,ecdsa-sha2-nistp384,ecdsa-sha2-nistp256,rsa-sha2-512,rsa-sha2-256,ssh-rsa,ssh-dss>
[2021-03-16 08:27:43] ssh_key_algorithm_allowed: Checking rsa-sha2-512 with list <ssh-ed25519-cert-v01@openssh.com,ecdsa-sha2-nistp521-cert-v01@openssh.com,ecdsa-sha2-nistp384-cert-v01@openssh.com,ecdsa-sha2-nistp256-cert-v01@openssh.com,rsa-sha2-512-cert-v01@openssh.com,rsa-sha2-256-cert-v01@openssh.com,ssh-rsa-cert-v01@openssh.com,ssh-dss-cert-v01@openssh.com,ssh-ed25519,ecdsa-sha2-nistp521,ecdsa-sha2-nistp384,ecdsa-sha2-nistp256,rsa-sha2-512,rsa-sha2-256,ssh-rsa,ssh-dss>
[2021-03-16 08:27:43] ssh_socket_unbuffered_write: Enabling POLLOUT for socket
[2021-03-16 08:27:43] packet_send2: packet: wrote [type=50, len=352, padding_size=11, comp=340, payload=340]
[2021-03-16 08:27:43] ssh_socket_pollcallback: Poll callback on socket 1772 (POLLOUT ), out buffer 0
[2021-03-16 08:27:43] ssh_socket_pollcallback: sending control flow event
[2021-03-16 08:27:43] ssh_packet_socket_controlflow_callback: sending channel_write_wontblock callback
[2021-03-16 08:27:44] ssh_socket_pollcallback: Poll callback on socket 1772 (POLLIN ), out buffer 0
[2021-03-16 08:27:44] ssh_packet_socket_callback: packet: read type 60 [len=320,padding=19,comp=300,payload=300]
[2021-03-16 08:27:44] ssh_packet_process: Dispatching handler for packet type 60
[2021-03-16 08:27:44] ssh_packet_userauth_pk_ok: Received SSH_USERAUTH_PK_OK/INFO_REQUEST/GSSAPI_RESPONSE
[2021-03-16 08:27:44] ssh_packet_userauth_pk_ok: Assuming SSH_USERAUTH_PK_OK
[2021-03-16 08:27:44] ssh_key_algorithm_allowed: Checking rsa-sha2-512 with list <ssh-ed25519-cert-v01@openssh.com,ecdsa-sha2-nistp521-cert-v01@openssh.com,ecdsa-sha2-nistp384-cert-v01@openssh.com,ecdsa-sha2-nistp256-cert-v01@openssh.com,rsa-sha2-512-cert-v01@openssh.com,rsa-sha2-256-cert-v01@openssh.com,ssh-rsa-cert-v01@openssh.com,ssh-dss-cert-v01@openssh.com,ssh-ed25519,ecdsa-sha2-nistp521,ecdsa-sha2-nistp384,ecdsa-sha2-nistp256,rsa-sha2-512,rsa-sha2-256,ssh-rsa,ssh-dss>
[2021-03-16 08:27:44] ssh_key_algorithm_allowed: Checking rsa-sha2-512 with list <ssh-ed25519-cert-v01@openssh.com,ecdsa-sha2-nistp521-cert-v01@openssh.com,ecdsa-sha2-nistp384-cert-v01@openssh.com,ecdsa-sha2-nistp256-cert-v01@openssh.com,rsa-sha2-512-cert-v01@openssh.com,rsa-sha2-256-cert-v01@openssh.com,ssh-rsa-cert-v01@openssh.com,ssh-dss-cert-v01@openssh.com,ssh-ed25519,ecdsa-sha2-nistp521,ecdsa-sha2-nistp384,ecdsa-sha2-nistp256,rsa-sha2-512,rsa-sha2-256,ssh-rsa,ssh-dss>
[2021-03-16 08:27:44] ssh_key_algorithm_allowed: Checking rsa-sha2-512 with list <ssh-ed25519-cert-v01@openssh.com,ecdsa-sha2-nistp521-cert-v01@openssh.com,ecdsa-sha2-nistp384-cert-v01@openssh.com,ecdsa-sha2-nistp256-cert-v01@openssh.com,rsa-sha2-512-cert-v01@openssh.com,rsa-sha2-256-cert-v01@openssh.com,ssh-rsa-cert-v01@openssh.com,ssh-dss-cert-v01@openssh.com,ssh-ed25519,ecdsa-sha2-nistp521,ecdsa-sha2-nistp384,ecdsa-sha2-nistp256,rsa-sha2-512,rsa-sha2-256,ssh-rsa,ssh-dss>
[2021-03-16 08:27:44] ssh_socket_unbuffered_write: Enabling POLLOUT for socket
[2021-03-16 08:27:44] packet_send2: packet: wrote [type=50, len=640, padding_size=19, comp=620, payload=620]
[2021-03-16 08:27:44] ssh_socket_pollcallback: Poll callback on socket 1772 (POLLOUT ), out buffer 0
[2021-03-16 08:27:44] ssh_socket_pollcallback: sending control flow event
[2021-03-16 08:27:44] ssh_packet_socket_controlflow_callback: sending channel_write_wontblock callback
[2021-03-16 08:27:44] ssh_socket_pollcallback: Poll callback on socket 1772 (POLLIN ), out buffer 0
[2021-03-16 08:27:44] ssh_packet_socket_callback: packet: read type 51 [len=32,padding=5,comp=26,payload=26]
[2021-03-16 08:27:44] ssh_packet_process: Dispatching handler for packet type 51
[2021-03-16 08:27:44] ssh_packet_userauth_failure: Partial success for 'publickey'. Authentication that can continue: keyboard-interactive
[2021-03-16 08:27:46] ssh_socket_unbuffered_write: Enabling POLLOUT for socket
[2021-03-16 08:27:46] packet_send2: packet: wrote [type=1, len=32, padding_size=11, comp=20, payload=20]
```

**Comment by kingToolbox** [comment] 2021-03-16 10:43
Nice to see you here, :smile: The problem has been confirmed, I will fix it as soon as possible, thank you!

**Comment by kingToolbox** [comment] 2021-03-18 07:10
This issue has been fixed. Since I don’t have a 2FA environment to test, please help me test. Just download `WindTerm_bugfix_#63.zip`, unzip and replace the same `WindTerm.exe`. If the test passes, I will release a new version together with other fixes. Thank you very much.

[WindTerm_bugfix_#63.zip](https://github.com/kingToolbox/WindTerm/files/6161949/WindTerm_bugfix_.63.zip)

**Comment by R60olus** [comment] 2021-03-18 07:54
Is Working like a charm!
![image](https://user-images.githubusercontent.com/62094884/111591265-83897f00-87c7-11eb-9a6f-e999f61133b9.png)

**Comment by kingToolbox** [comment] 2021-03-18 10:07
Great:smile:, but this fix caused the automatic login to fail. So after continuing to fix all known bugs, v2.0.2 will be released within one to two days. Please download and use it. I will update the progress here. Thank you very much!

**Comment by kingToolbox** [comment] 2021-03-23 12:10
The fix has been released, please download the new version [2.0.2](https://github.com/kingToolbox/WindTerm/releases/tag/2.0) and check, thank you.

**Comment by R60olus** [comment] 2021-03-23 12:33
No Problems so far, works really nicely. Thanks 😃 
![image](https://user-images.githubusercontent.com/62094884/112146782-44e73080-8bdc-11eb-8b80-ba4a77373b95.png)

**Comment by kingToolbox** [comment] 2021-03-23 13:17
Thank you so much for responding so quickly. In addition to fixing errors, it also provides new 2FA automatic login, of course, only when the verification code does not change. :smile:

This issue will be closed and welcome to continue submitting new issues and feature requests, thank you.

**Closed by kingToolbox** 2021-03-23 13:17 UTC
Labels: bug
