### ISSUE TITLE
Timestamp in the log file is inaccurate

### ISSUE THREAD

**Issue by darkhandz** [kingToolbox/WindTerm#511] opened 2022-02-14 12:30 UTC
WindTerm 2.3.0 PreRelease 4
win10 19044.1469
Session: Serial

I found the relative time in logging function is not same as margin's.
Like the screenshot below, in fact, the higlighted lines are about to print out at the same time (margin time is right), but log file show that they were output at different time (line 3039 is about 20s later than line 3038, and 3040 is similar).

![image](https://user-images.githubusercontent.com/2143333/153862770-60279d9e-f2ad-4f44-b16b-9a5744adad16.png)

**Comment by kingToolbox** [comment] 2022-02-16 02:50
Duplicate of #497

The timestamp in the log is the time when the log is written to disk, so there is a delay compared to the time when the text is received.

I will improve this in the next bugfix version `WindTerm_2.3.1`, which is expected to be released this week. Please stay tuned, thank you.

**Comment by kingToolbox** [comment] 2022-02-23 02:56
I am happy to inform you that [WindTerm_2.3.1](https://github.com/kingToolbox/WindTerm/releases/tag/2.3.0) has been released and this issue has been fixed. Please download and check it. If there are still bugs, please let me know, thank you.

**Comment by darkhandz** [comment] 2022-02-23 05:59
Finally, the new verison comes out, thanks for your hard work.👏

I found something interesting in v2.3.1, like the pic below, the log file shows line 1577 and 1578 has different timestamp, but session windows shows they are same, I guess maybe log file is more accurate?
And in the blue rect, line 1595 1598 1600 shows an early timestamp, is this cause by the invisible character (%v) ?

![image](https://user-images.githubusercontent.com/2143333/155267538-07958f22-7547-4505-8919-fd9c83c8521c.png)

**Comment by kingToolbox** [comment] 2022-02-23 07:46
You are really very observant. :smile: 

As you analyzed, the timestamps in the logs are more precise. But why are the ones shown on the screen less accurate?

Before we talk about this, we need to understand how the server refreshes the screen. In fact, the server doesn't refresh line by line, but wherever there is a change. That's why those blue lines are older than the context, because they are empty lines that don't need to be updated again after the first created (`%v` is a bug).

Another feature is that the server sometimes does not just refresh the new and deleted text, but refreshes more text, or even the whole screen. As shown in the screen, all the lines were output once at `12:08:43:990`, but somehow some of them were refreshed again at `12:08:44:007`. All of this is well recorded in the log.

Since most of the text printed before and after was the same, `WindTerm` compared the text when drawing the screen and discarded the same parts to improve performance, in addition to avoiding visual changes for the user. So for the second 
`12:08:44:007` update above, it was discarded completely and the timestamps definitely remains unchanged. After all, people prefer static text content.

There are also some designs and techniques that will not be described in detail. I believe almost no other terminals can display the time of each line as well as `WindTerm`. But in order to develop this feature well, it took a lot of time to polish it.

**Comment by darkhandz** [comment] 2022-02-23 11:06
I hope this issue doesn't take up too much of your time🤣
Since the log file is precise enough, it satisfy my demand, margin timestamp is just for realtime reference.

**Comment by kingToolbox** [comment] 2022-02-23 12:38
Not at all, as this issue should have been resolved and will be closed. :smile: You are welcome to continue to file new feature requests and bugs, thank you.

**Closed by kingToolbox** 2022-02-23 12:38 UTC
Labels: duplicate
