### ISSUE TITLE
Keyboard is stuck when downloading files

### ISSUE THREAD

**Issue by kinloonglee** [kingToolbox/WindTerm#483] opened 2022-01-27 08:14 UTC
![image](https://user-images.githubusercontent.com/30849180/151317509-6b530a12-746f-4145-90ed-0248bb731b86.png)

图中我是在上传的同时,一直按回车键,  非常卡,隔几秒钟,才会刷新一下,

**Comment by kingToolbox** [comment] 2022-01-28 18:57
Duplicate of #167 

This is a normal phenomenon, because downloading files and sending commands use the same socket, which will interfere with each other. You can refer to [this comment](https://github.com/kingToolbox/WindTerm/issues/167#issuecomment-902190981) for details. Thank you.

**Closed** 2022-01-29 01:11 UTC
