### ISSUE TITLE
Moving window to higher DPI monitor garbles text

### ISSUE THREAD

**Issue by hapklaar** [kingToolbox/WindTerm#78] opened 2021-04-08 20:46 UTC
Before moving, on 1440p monitor:
![image](https://user-images.githubusercontent.com/7703320/114093842-e6000780-98bb-11eb-8d2c-ea7673d6afa4.png)
After moving, on 2160p monitor:
![image](https://user-images.githubusercontent.com/7703320/114093946-0203a900-98bc-11eb-80e0-ebf7202ab761.png)

**Comment by kingToolbox** [comment] 2021-04-08 21:30
Thank you. I think this is the same bug of #73. I will fix this in the next version.

**Comment by kingToolbox** [comment] 2021-05-27 22:26
Sorry to keep you waiting. [WindTerm_2.1.0_Prerelease_3](https://github.com/kingToolbox/WindTerm/releases/tag/2.1) has just been released and this issue has been fixed. You can download and check it now. Thank you.

**Comment by kingToolbox** [comment] 2021-06-28 07:45
Hello, the previous fix is defective, I have tried to fix it again, please download [WindTerm_2.1.0_Prerelease_5](https://github.com/kingToolbox/WindTerm/releases/tag/2.1-prerelease) and check it, thank you.

**Comment by lpadula** [comment] 2021-07-01 12:25
Hi, moving window on other monitor with 125% scale, shows same problem!

**Comment by kingToolbox** [comment] 2021-07-01 13:08
@lpadula, Thank you. It seems that the problem is still there. I tried it on Windows 7 without any problems, but Windows 7 does not support two monitors to set different scale values. I know Windows 10 supports, but I don’t have windows 10 with two monitors available yet. Once there is an environment, I will try to solve it as soon as possible. 

By the way, after dragging to another monitor, can the text be displayed normally by `menubar - view - zoom in` or `menubar - view - zoom out`?

**Comment by lpadula** [comment] 2021-07-01 13:11
Yes! The problem is with the terminal view.

**Comment by kingToolbox** [comment] 2021-07-01 13:59
I see. If `zoom in` or `zoom out` can **make the abnormally displayed text display normally**, then the most likely problem is that the monitor  change is not detected correctly. Because if it detects a monitor change, WindTerm_Prerelease_5 will automatically adjust the text display like zooming.

I will check why WindTerm failed to receive the monitor change event correctly, maybe it can fix this problem as soon as possible, thank you very much for your assistance! Once there is progress, I will update here to let you know.

**Comment by kingToolbox** [comment] 2021-07-17 17:02
Hello, [WindTerm_2.1.0](https://github.com/kingToolbox/WindTerm/releases/tag/2.1) has just been released. I re-written the related code and also did a simulation test, I think this issue should has been fixed. You can download and check it now. Thank you.

**Comment by kingToolbox** [comment] 2021-07-20 16:36
The issue should have been fixed in the new [WindTerm_2.1.0](https://github.com/kingToolbox/WindTerm/releases/tag/2.1) and self-test passed. Please reopen this issue if it is still valid. Thank you.

**Closed by kingToolbox** 2021-07-20 16:36 UTC
Labels: bug
