### ISSUE TITLE
multiple sessions input

### ISSUE THREAD

**Issue by ArthurZangCN** [kingToolbox/WindTerm#87] opened 2021-04-25 06:02 UTC
Whether multiple sessions will be supported to be input at the same time, like xshell, not in the sender as it is now.

**Comment by kingToolbox** [comment] 2021-04-25 07:13
Is it more convenient, or is it for other reasons? 

The current design should be able to meet the needs of simultaneous operation of multiple sessions. **Especially in the `sender` pane, you can have multiple senders at the same time (click the `plus` toolbar button or `Alt+=`), and each `sender` can send commands to different selected sessions group at the same time.** And after inutting, you can directly press the `Alt+Enter` key to send immediately, which should also be very convenient. 

BTW, It seems that the `<Alt+Enter>` key does not work anymore. If confirmed, it will be fixed in the next version.

**Comment by ArthurZangCN** [comment] 2021-04-26 00:17
> Is it more convenient, or is it for other reasons?
> 
> The current design should be able to meet the needs of simultaneous operation of multiple sessions. **Especially in the `sender` pane, you can have multiple senders at the same time (click the `plus` toolbar button or `Alt+=`), and each `sender` can send commands to different selected sessions group at the same time.** And after inutting, you can directly press the `Alt+Enter` key to send immediately, which should also be very convenient.
> 
> BTW, It seems that the `<Alt+Enter>` key does not work anymore. If confirmed, it will be fixed in the next version.

yes,  the <Alt+Enter> key does not work anymore.

the multiple sessions input is more convenient . for example when i modify some code file or configure file，or i need wait response, or i find long path cmd (tab key) . but to do that is very diffcult  in sender.

**Comment by kingToolbox** [comment] 2021-04-26 05:48
OK, I see. I knew this feature of XShell before, I just think its design usually makes the operation more complicated.

First you need click "Send Key Input To All Sessions", if you happen to need to send keys to all sessions, it is very convenient, but often only part of them require input, then you must click `Off` one by one to cancel the unwanted sessions. For example, there are currently ten sessions and only three need to be typed, so you need to cancel seven times. Of course, you can create a new window to put the required sessions together, but it is still very cumbersome. I don’t know if you have encountered this problem, and how did you solve it? 

The feature itself is very good, thank you. I will try to find if there is a new and better design to meet your needs.

**Comment by kingToolbox** [comment] 2021-04-26 05:49
OK, I see. I knew this feature of XShell before, I just think its design usually makes the operation more complicated.

First you need click "Send Key Input To All Sessions", if you happen to need to send keys to all sessions, it is very convenient, but often only part of them require input, then you must click `Off` one by one to cancel the unwanted sessions. For example, there are currently ten sessions and only three need to be typed, so you need to cancel seven times. Of course, you can create a new window to put the required sessions together, but it is still very cumbersome. I don’t know if you have encountered this problem, and how did you solve it? 

The feature itself is very good, thank you. I will do it, and I will try to find if there is a new and better design to meet your needs.

**Comment by ArthurZangCN** [comment] 2021-04-26 05:53
> Is it more convenient, or is it for other reasons?
> 
> The current design should be able to meet the needs of simultaneous operation of multiple sessions. **Especially in the `sender` pane, you can have multiple senders at the same time (click the `plus` toolbar button or `Alt+=`), and each `sender` can send commands to different selected sessions group at the same time.** And after inutting, you can directly press the `Alt+Enter` key to send immediately, which should also be very convenient.
> 
> BTW, It seems that the `<Alt+Enter>` key does not work anymore. If confirmed, it will be fixed in the next version.

for example  when i opened ten sessions，and every one starting iostat or top，when i stop it ， i must be do stop in every session.

**Comment by ArthurZangCN** [comment] 2021-04-26 06:05
> OK, I see. I knew this feature of XShell before, I just think its design usually makes the operation more complicated.
> 
> First you need click "Send Key Input To All Sessions", if you happen to need to send keys to all sessions, it is very convenient, but often only part of them require input, then you must click `Off` one by one to cancel the unwanted sessions. For example, there are currently ten sessions and only three need to be typed, so you need to cancel seven times. Of course, you can create a new window to put the required sessions together, but it is still very cumbersome. I don’t know if you have encountered this problem, and how did you solve it?
> 
> The feature itself is very good, thank you. I will do it, and I will try to find if there is a new and better design to meet your needs.

Yes, I think it's a problem, but relative to the convenience brought by this feature, I can tolerate this problem. As you said, I will create a new window. At the same time, I think this characteristic is the only difference between xshell and other shell terminals.

Thank you very much for your attention.

**Comment by kingToolbox** [comment] 2021-04-26 07:25
My pleasure.

I will probably strive to complete this feature by improving `sender`. After all, `sender` already has some facilities, such as selecting the target sessions, because I definitely don't want to cancel seven sessions first in order to select three sessions :laughing:, and the two features are relatively similar. This can also save some development time, I think you will be able to use this feature in the next **prerelease** version soon, and its release time is likely to be this week.

**Comment by kingToolbox** [comment] 2021-05-13 18:02
Hi, @ArthurZangCN. I am designing `synchronous input`. I would like to ask if you only need to operate one set of sessions during synchronous input in actual work, or do you need to operate multiple sets of sessions? Just like sessions 1, 2, and 3 are set as a set of synchronization targets, and sessions 4, 5, and 6 are set as another set of synchronization targets. Will there be multiple sets of synchronization requirements?  Thanks for your advice.

**Comment by kingToolbox** [comment] 2021-05-13 18:23
Another question is, will the synchronization input usually used for a long time, or is it only temporarily used to enter a few commands? Thank you.

**Comment by ArthurZangCN** [comment] 2021-05-14 00:22
> Hi, @ArthurZangCN. I am designing `synchronous input`. I would like to ask if you only need to operate one set of sessions during synchronous input in actual work, or do you need to operate multiple sets of sessions? Just like sessions 1, 2, and 3 are set as a set of synchronization targets, and sessions 4, 5, and 6 are set as another set of synchronization targets. Will there be multiple sets of synchronization requirements? Thanks for your advice.

i only need to operate one set of sessions during synchronous input in actual work, because if multiple sets of sessions in one window, will has misoperation, so if i have multiple sets of sessions, i will have diffient window.

**Comment by kingToolbox** [comment] 2021-05-14 00:35
Ok, I see, it seems that there is still a need to operate multiple sets of sessions at the same time. thank you very much.

**Comment by ArthurZangCN** [comment] 2021-05-14 00:40
> > Hi, @ArthurZangCN. I am designing `synchronous input`. I would like to ask if you only need to operate one set of sessions during synchronous input in actual work, or do you need to operate multiple sets of sessions? Just like sessions 1, 2, and 3 are set as a set of synchronization targets, and sessions 4, 5, and 6 are set as another set of synchronization targets. Will there be multiple sets of synchronization requirements? Thanks for your advice.
> 
> i only need to operate one set of sessions during synchronous input in actual work, because if multiple sets of sessions in one window, will has misoperation, so if i have multiple sets of sessions, i will have diffient window.

Usually, I'm more used to using this feature than senders, because what you see is what you get.I think senders are more suitable for timing tasks.
thanks for you，I'm introducing this software to my friends. I think it's the best free shell tool I've ever used.

> Another question is, will the synchronization input usually used for a long time, or is it only temporarily used to enter a few commands? Thank you.

Usually, I'm more used to using this feature than senders, because what you see is what you get.I think senders are more suitable for timing tasks.
thanks for you，I'm introducing this software to my friends. I think it's the best free shell tool I've ever used.

**Comment by kingToolbox** [comment] 2021-05-27 22:39
I am very happy to tell you that I have completed this feature in the new [WindTerm_2.1.0_Prerelease_3](https://github.com/kingToolbox/WindTerm/releases/tag/2.1). I am very satisfied with the design of this feature, you can read [Sync Input](https://kingtoolbox.github.io/2021/05/27/sync-input/) to learn more. I believe it is very convenient to use. 

Please download and try it, If you have any suggestions, please let me know. Thank you.

BTW, The bug that `<Alt+Enter>` key does not work in the `Sender` pane has also been fixed.

**Comment by ArthurZangCN** [comment] 2021-05-28 04:17
> I am very happy to tell you that I have completed this feature in the new [WindTerm_2.1.0_Prerelease_3](https://github.com/kingToolbox/WindTerm/releases/tag/2.1). I am very satisfied with the design of this feature, you can read [Sync Input](https://kingtoolbox.github.io/2021/05/27/sync-input/) to learn more. I believe it is very convenient to use.
> 
> Please download and try it, If you have any suggestions, please let me know. Thank you.
> 
> BTW, The bug that `<Alt+Enter>` key does not work in the `Sender` pane has also been fixed.

This is really good news. You are a very nice developer. I will download and use it immediately. If have any questions, I will contact you again.

**Comment by kingToolbox** [comment] 2021-05-28 05:34
I hope you like this design. :smiley: When designing, I paid particular attention to ensuring that sessions can join or leave synchronous input at any time. I think this is very important for the freedom of use, and I rarely see this in the design of other similar products. 

As for the `Sender`, its feature development has not yet been completed, and there are still many interesting and useful features waiting to be developed. After the completion, I believe that the `Sender` will be more powerful, especially after adding the script feature. Judge and perform different operations based on the returned content, which cannot be done by synchronous input. As you said, both have their own usage scenarios.

**Comment by kingToolbox** [comment] 2021-05-28 05:36
I hope you like this design. :smiley: When designing, I paid particular attention to ensuring that sessions can join or leave synchronous input at any time. I think this is very important for the freedom of use, and I rarely see this in the design of other similar products. 

As for the `Sender`, its feature development has not yet been completed, and there are still many interesting and useful features waiting to be developed. After the completion, I believe that the `Sender` will be more powerful, especially after adding the script feature. Judge and perform different operations based on the returned content, which cannot be done by synchronous input. As you said, both have their own usage scenarios.

**Comment by ArthurZangCN** [comment] 2021-05-31 08:12
I used it for a few days, totally exceeding the expectation. It's really wonderful, much better than xshell. Thank you very much for this design.
Looking forward to the perfect sender.

**Comment by kingToolbox** [comment] 2021-06-15 21:25
I am glad you like it. For better use, I continue to develop the pause and resume function to temporarily disable synchronization without leaving the current synchronization channel. In addition, for the convenience of viewing the contents of multiple sessions,  the features of splitting and moving session tabs to another tab group has also been added.

You can now download the latest [WindTerm_2.1.0_Prerelease_4](https://github.com/kingToolbox/WindTerm/releases/tag/2.1-prerelease) and try it out. Thank you.

**Comment by kingToolbox** [comment] 2021-06-30 19:36
Everything about this feature request has been implemented. This issue will be closed and welcome to continue submitting new issues and feature requests, thank you.

**Closed by kingToolbox** 2021-06-30 19:36 UTC
Labels: feature
