### ISSUE TITLE
WindTerm don't  work well with "screen" command

### ISSUE THREAD

**Issue by skbeh** [kingToolbox/WindTerm#216] opened 2021-10-02 09:22 UTC
Reproduce step:
1. Start a ssh session and run `screen`.
2. Exec some command with a lot of output like `ps`.
3. Scroll the page up and the output from then will disappear, there is only the line with `screen`.

**Comment by kingToolbox** [comment] 2021-10-02 16:26
Thank you, I will investigate this issue. And I will update the progress here.

**Comment by hughxing** [comment] 2021-11-05 07:25
I meet this too. And the screen would not update with 'screen' command on some machine, it would not work at all.

**Comment by kingToolbox** [comment] 2021-11-06 12:45
I have confirmed this issue and will fix it immediately after the `WindTerm_2.2.0_Prerelease_4` is released. The `WindTerm_2.2.0_Prerelease_4` will be released today, and this bugfix version is expected to be released next week. Please stay tuned, thank you.

**Comment by kingToolbox** [comment] 2021-11-07 18:42
As promised, I started to solve this problem after I released `WindTerm_2.2.0_Prerelease_4`. There are two problems, one is that "Aborted because of window size change." will be displayed after starting `screen`, and the other is that the scrolling history is lost. But after careful analysis, I think neither of these is wrong. 

For the first problem, if `Term` is set to `xterm-256color`, which is the default `Term` of new session in `WindTerm`, this problem will occur. But this is caused by `screen`. For details, please refer to [Debian Bug 134198](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=134198). If you set it to other term types, such as `xterm`, `vt220` and so on, this problem will gone.  

For the second problem, When `screen` detects that `Term` is set to `xterm` or `xterm-256color`, it will enable the `alternate screen` feature, and `alternate screen` does not support scroll history by nature. 

I used `PuTTY` to test and set its `Configuration Dialog - Connection - Data - Terminal-type string` to `xterm`, and the test results are consistent with `WindTerm`. The test result of the terminal `xterm` is the same too.

And I also tested that when the `Term` of the session is set to `vt220`, everything in `WindTerm` is Ok. So if you need to use `screen` in `WindTerm`, you can try to set the `Term` of your session to `vt220`, `vt340`, `vt420` or `vt520`. 

In addition, I also tried to added `altscreen off` to `~/.screenrc` and `/etc/.screenrc` according to the [screen manual](https://www.gnu.org/software/screen/manual/screen.html#index-altscreen) and hoped to be able to turn off the `altscreen` feature, but I failed:

> Command: altscreen state
>     (none)
>     If set to on, "alternate screen" support is enabled in virtual terminals, just like in xterm. Initial setting is ‘off’. 

If you can set it `off` successfully, please let me know. please let me know. Thank you.

**Comment by hughxing** [comment] 2021-11-10 08:36
Thank you.
I had try vt220, vt420, vt520, it's ok (vt420/vt520 is not support in some machine).
And I try added "altscreen on" to screenrc file, it also not work with xterm.

**Comment by kingToolbox** [comment] 2021-11-10 11:44
`Screen` has been around for some years, and now most people use `Tmux`.

Anyway, this issue has been solved and will be closed. If you have new feature requests or bugs, welcome to file a new 
 issue, thank you.

**Closed by kingToolbox** 2021-11-10 11:44 UTC
Labels: bug
