### ISSUE TITLE
Remove the "Shell Sessions" folder

### ISSUE THREAD

**Issue by tom472** [kingToolbox/WindTerm#38] opened 2020-12-24 16:20 UTC
Is there a way to permanently remove the "Shell Sessions" folder.
The entries with the `admin:cmd` `admin:powershell` etc. 

I have selected the folder and clicked remove and every time I reopen WindTerm the folder comes back.
I have also directly deleted the entries from the: `WindTerm\profiles\default.v10\terminal\user.sessions` file.
The folder comes back again upon a reopen of WindTerm.
And additionally I have tried deleting them directly from the file above and deleting the: `WindTerm\profiles\default.v10\terminal\reopen.history` file as well.
The folder still comes back again upon a reopen of WindTerm

I am not interested in having that folder and it's entries in my list, is there a way to permanently remove them from the interface.

Thanks

**Comment by kingToolbox** [comment] 2020-12-24 16:47
This should be a bug. And It should be introduced when developing the Linux version.

By design, shell sessions will be imported only when the application is initially run. And only when the folder **profiles** does not exist, it will be considered as the first run.

In normal use, you only need to use **remove** to delete group and sessions, And there is no need to directly manipulate the configuration file **user.sessions**, WindTerm will help you do this.

Today a new v1.9.2 will be released, and I will fix this bug in this version.

**Comment by tom472** [comment] 2020-12-24 18:51
I should have mentioned that this was on the windows version -- I'll look for 1.9.2 and test in that.

Thanks

**Comment by kingToolbox** [comment] 2020-12-25 08:47
The new version 1.9.2 has been released, please download and check, thank you.

I checked the code. The original intention of writing this code is to assist old versions to be automatically upgrated to v1.8 and higher. This version newly supports opening Cmd, PowerShell as administrator. So even if there is already exists folder "profile", as long as no admin shell session is detected, it will be automatically imported. Since you happen to not need this, it becomes a bug instead.

When writing this code, it has been set to automatically invalidate to version 2.0. Now this code has been deleted.

**Comment by tom472** [comment] 2020-12-26 02:36
Looking good - thanks for the quick update.

**Comment by kingToolbox** [comment] 2020-12-26 04:25
Sure thing. I hope you enjoy and please let me know if you have issues, ideas, comments or any sort of feedback!

**Closed by kingToolbox** 2020-12-26 04:25 UTC
Labels: bug
