### ISSUE TITLE
Remote mode line wrapping

### ISSUE THREAD

**Issue by eugenov** [kingToolbox/WindTerm#285] opened 2021-11-22 14:42 UTC
Hello!
Long wrapped output lines (folded ones) are treated like multi-lined, when copy-pasted back to terminal.

**Comment by kingToolbox** [comment] 2021-11-22 16:24
This is probably caused by the mistakenly clearing the wrap flag of subline when fixing #260. Now this problem has been fixed and will be released in a new `WindTerm_2.2.1` bugfix version soon. Thank you.

**Comment by kingToolbox** [comment] 2021-11-24 19:38
I am happy to inform you that [WindTerm_2.2.1](https://github.com/kingToolbox/WindTerm/releases/2.2) has been released and this issue has been fixed, please download and check it, thank you.

**Closed** 2021-11-25 07:10 UTC
Labels: bug

**Comment by SadarSSI** [comment] 2022-03-03 12:47
a suggestion for remembering the clink (_[https://github.com/chrisant996/clink](url)_) history this is set almost like bash with the .inputrc.

Very practical under Windows for the cmd.exe which becomes a little less stupid! ;-))

**Comment by kingToolbox** [comment] 2022-04-21 17:10
@SadarSSI 
Thank you. `WindTerm` will implement the `History` feature and record all the commands the user has entered, and use it for autocomplete, paste and other functions. And it does not depend on any third-party tools.

**Comment by kingToolbox** [comment] 2022-06-22 20:38
@SadarSSI 
The [WindTerm_2.5.0_Prerelease_2](https://github.com/kingToolbox/WindTerm/releases/tag/2.5-prerelease) version already supports recording history commands. You can use it and feel free to give any comments or suggestions.

BTW:
Subsequent versions will automatically import history commands from the `clink` or `bash` configuration files.
