### ISSUE TITLE
创建传输后命令输入延迟

### ISSUE THREAD

**Issue by Rinnsoui** [kingToolbox/WindTerm#457] opened 2022-01-18 03:54 UTC
从linux上下载文件，在下载中，如果输入命令，命令会延迟大概2秒或者3秒后才出现。

**Comment by kingToolbox** [comment] 2022-01-19 05:53
Duplicate of #167

This is normal. Since the transmission of files and commands share a socket, there will inevitably be delays. Almost every SSH client has this problem. You can read [this comment](https://github.com/kingToolbox/WindTerm/issues/167#issuecomment-902190981) for a more detailed explanation.

**Comment by Rinnsoui** [comment] 2022-01-19 07:52
好的，明白~ 然后还有个问题，就算工具查找的时候 不能连续输入，会覆盖之前的输入，得按一下前进或者后退才可以继续输入！
第二个是查询到后点箭头跳下一个会没有反应

**Comment by kingToolbox** [comment] 2022-01-19 08:04
The two problem you mentioned has been fixed in the latest [WindTerm_2.3.0_Prerelease_2](https://github.com/kingToolbox/WindTerm/releases/2.3-prerelease) version. Please update and check it, thank you.

This issue will be closed, and you are welcome to continue submitting new issues. :smile:

**Closed by kingToolbox** 2022-01-19 08:04 UTC

**Comment by Rinnsoui** [comment] 2022-01-19 08:24
抱歉，刚刚去看了才知道有最新版，然后赶紧回来想告知问题以解决，不占用你宝贵得时间来回复以修复的问题，没想到您已经回复 😄
