### ISSUE TITLE
Can't use alt+o

### ISSUE THREAD

**Issue by huai168an** [kingToolbox/WindTerm#120] opened 2021-07-09 02:18 UTC
"terminal.askBeforeCloseWindow" : false,
    "terminal.restoreLastViews" : false,

After configuring these two items, the terminal cannot use alt+o to open the command interface and cannot search for a session or address, but after opening a shell, alt+o works normally

Suggestion：
After opening the terminal focus at least in the "search or enter address" of the "standard" (this must have ah, otherwise can not keyboard quick operation)
Or, as said before, provide the ability to open a shell by default

Before Prerelease_5 including version 5, I keep gitbash by default and remind to save it every time I close it. So every time I open it, alt+o works fine and opens the desired address quickly.

What I always wanted was to open the default one shell and close it without reminding to save, but prompting under multiple tabs whether to close all tabs（Prevent misoperation ）. The ability to save the shell doesn't make a lot of sense.

In fact, in windows, in most cases open a terminal, nothing more than the use of windows commands or ssh to connect a host, rather than multiple hosts, especially the management of linux need to pass jumpserver, at most open jumpserver this one host, so when opening a terminal, there are multiple tabs under the function, the default open cmd or gitbash is the best, and then quickly open the desired session.

**Comment by kingToolbox** [comment] 2021-07-09 04:09
After restarting, is your caret in the Sender's text widget? If it is, then the shortcut key is parsed by Sender‘s text widget. Because the action of `Alt+O` in the text widget is not specified by default, so `Alt+O` will be invalid. You can try to close sender, or move caret to other widgets, then you can use `Alt+O` and `address bar` normally. I will also improve this in the next version. Once no tab is opened after restarting, I will put the caret in `Address Bar` for immediate input. 

As for opening `Shell` by default after restarting, this will be realized by the `Pin Tab` feature. After this feature is completed, any pinned session tabs will be restored after restarting, without being restricted by `terminal.restoreLastViews`. At that time, you can pin a `Shell` to meet your needs. This feature is expected to be completed in the 2.3 or 2.4 version.

If someone is worried about closing WindTerm by mistake, it is recommended to keep `terminal.askBeforeCloseWindow` set to `true`, otherwise we still need to design a new dialog box to ask someone if he/she really need to exit, which will cause unnecessary repetition in the design. 

Finally, as far as I know, WindTerm is more used as **SSH client** than **terminal**. WindTerm is a full-featured SSH client, including the [JumpServer](https://kingtoolbox.github.io/2021/03/11/proxy-jump-server/) feature you mentioned. So if you need use SSH, just use WindTerm instead of opening `cmd` and input `ssh host`, which will be more convenient. You can read [here](https://kingtoolbox.github.io/) to learn more.

**Comment by huai168an** [comment] 2021-07-09 04:14
![图片](https://user-images.githubusercontent.com/52577307/125022382-26d00e00-e0af-11eb-989a-01e9427303fb.png)
This is the default screen that opens
I turned off sender in the interface

**Comment by huai168an** [comment] 2021-07-09 04:21
“So if you need use SSH, just use WindTerm instead of opening cmd and input ssh host, which will be more convenient. ”
It must be a translation problem, not to translate my meaning，oh，no  ：（

**Comment by kingToolbox** [comment] 2021-07-09 04:40
I just tried it according to your interface layout, the shortcut key `Alt+O` can open the `Command Palette`, and a new `Cmd` tab will also be opened by default at startup. So can you try a few more times?

Don't worry about the language, I think our communication has always been smooth. :smile:

**Comment by huai168an** [comment] 2021-07-09 05:05
"terminal.askBeforeCloseWindow" : false,
"terminal.restoreLastViews" : false,
configuring these two items ？

**Comment by kingToolbox** [comment] 2021-07-09 09:07
Yes, you are right, thank you. I checked it again. when setting `"terminal.askBeforeCloseWindow": false` and `"terminal.restoreLastViews": false`, the problem you mentioned was indeed reproduced. I will fix this bug.

The temporary workaround now is that you can click the address bar with the mouse to set the focus to the address bar, and then you can use `Alt+O` normally.

**Comment by kingToolbox** [comment] 2021-07-14 17:31
Hello, [WindTerm_2.1.0_Prerelease_7](https://github.com/kingToolbox/WindTerm/releases/tag/2.1-prerelease) has finally been released and this issue should have been fixed. You can download and check it now. Thank you.

**Comment by kingToolbox** [comment] 2021-07-17 17:26
Hello, you can download [WindTerm_2.1.0](https://github.com/kingToolbox/WindTerm/releases/tag/2.1) and check it now, thank you.

**Comment by kingToolbox** [comment] 2021-07-20 16:31
The issue has been fixed in [WindTerm_2.1.0](https://github.com/kingToolbox/WindTerm/releases/tag/2.1) and self-test passed. Please reopen this issue if it is still valid. Thank you.

**Closed by kingToolbox** 2021-07-20 16:31 UTC
Labels: feature
