### ISSUE TITLE
Passwords trouble.

### ISSUE THREAD

**Issue by SlaviusPrime** [kingToolbox/WindTerm#105] opened 2021-06-01 07:43 UTC
The program itself changes the unlock password and master password.
How to fix it?

**Comment by Liuhongdan** [comment] 2021-06-14 10:04
My master password also changed today afternoon after restart Windterm. Not sure why.

**Comment by kingToolbox** [comment] 2021-06-15 22:28
Sorry for the late reply, I just returned from vacation. I will analyze the encryption module. Because it never happened before, it may be caused by bugs in the newly added password change feature. I will try to fix this error as soon as possible. Thank you.

**Comment by Liuhongdan** [comment] 2021-06-16 02:51
Just tested two different versions that I'm still using.
Version 2.0.0 is still ok. 
Version 2.1.0 P2 got master password issue.
Can I copy master password from 2.0.0 to 2.10. P2 ?

**Comment by kingToolbox** [comment] 2021-06-16 06:37
No, I don't think it will work, unless you copy both `profiles\default.v10\user.config` and `profiles\default.v10\terminal\user.sessions` from `v2.0.0` to `v2.1.0 prerelease` at the same time.

I have conducted an analysis, but unfortunately, I have not been able to find the problem. I will continue to analyze. 

In terms of design, there are two possibilities for password failure, one is that the fingerprint (`application.fingerprint` in `profiles\default.v10\user.config`) has been tampered with, and the other is that the encrypted login information of the session (`session.autoLogin` in `profiles\default.v10\terminal\user.sessions`) has been tampered with. When the master password has been set, once the wrong password is entered, it will be rejected, and the wrong password will not be used for encryption and decryption, and will not be saved too. 

The fingerprint will only be automatically generated when the master password is set for the first time, and there will be no code to modify it afterwards. The encrypted login information will only be re-encrypted with the new password when using the master password change function. In addition, there will be no code to modify it too. So it is still unknown what operation caused the master password to be changed, and WindTerm itself should not be able to change the password.

**Comment by SlaviusPrime** [comment] 2021-06-16 14:48
The last week the problem has not been repeated. this is strange

**Comment by SlaviusPrime** [comment] 2021-06-17 09:34
Thank you!
I like WindTerm.

**Comment by huai168an** [comment] 2021-06-21 02:23
My master password has also been changed and there is no backup, how do I restore it?

**Comment by huai168an** [comment] 2021-06-21 02:55
> 我的主密码也被改了：（

Repeated the problem ：）
profiles\default.v10\terminal\user.sessions
![image](https://user-images.githubusercontent.com/52577307/122700842-a15ef800-d27e-11eb-8997-1f64a8166ca6.png)
![image](https://user-images.githubusercontent.com/52577307/122700853-a754d900-d27e-11eb-93a1-eeb6bf8c62a8.png)

The other sessions are not modified, but this session in the picture above is modified

The right side is abnormal，windterm 

I'm debugging git bash ssh config file, windterm seems to have automatically read the config file or saved the connection information, resulting in a session exception, after restoring the previous session is normal

**Comment by huai168an** [comment] 2021-06-21 02:58
a

**Comment by kingToolbox** [comment] 2021-06-21 21:26
@huai168an, thank you. But yours doesn't look like the password has been reset by mistake. I noticed that the `session.autoLogin` on the right is empty. I think you may re-import the OpenSSH sessions? If it is, it will clear the existing sessions data first and then re-import it, so there will be no `session.autoLogin`.

**Comment by huai168an** [comment] 2021-06-21 23:39
i'm not re-import the OpenSSH sessions,
It should be in the connection process session configuration changed, resulting in session information modified, and, identityfilepath path no longer exists, at least this state, the master password is abnormal

**Comment by kingToolbox** [comment] 2021-06-22 21:17
@huai168an. Ok, I see. My analysis conclusion is as follows, please tell me if my understanding is correct. Thank you.

- In the abnormal session configuration, `session.autoLogin` is reset to an empty string.
- In the abnormal session configuration, `session.identityfilePath` is set to a pem file.
  BTW, did you set this manually, or did WindTerm automatically import it from the OpenSSH configuration file? I noticed that the configuration on the left does not seem to have this item. This `session.identityfilePath` should actually be empty, right? 
- Only one session configuration has been tampered with, the others have not been affected and are still correct. 
- The `application.fingerprint` in `user.config` has not been modified.

**Comment by huai168an** [comment] 2021-06-23 01:10
yes, but there is no manual modification ，WindTerm automatically import it from the OpenSSH configuration file，The pem file existed before, then the pem file was deleted，Only one session was modified during the test, and the others were not tested

**Comment by kingToolbox** [comment] 2021-06-23 02:40
I think there should be no problems with other sessions because other sessions configuration have not been modified. In addition, after you restore this session configuration, it returns to normal. This shows that the master password is still correct. 

Thank you very much for your help, the information you provided is very important for the fix. I think I know how to fix it now, but I still need to do some tests to verify the solution. I will try to fix this problem in the next version. The release date should be this week.

**Comment by Liuhongdan** [comment] 2021-06-23 02:44
2.0.0 P4 got same issue now.
How did it happen:
1. Didn't close yesterday night.
2. Closed laptop lid
3. Opened lid today and started to use WindTerm
4. It was screen lock and asked master password. Keyed in password, but password was not correct.

Already restored previous profile backup. Will try again.

**Comment by kingToolbox** [comment] 2021-06-23 11:47
@Liuhongdan Do nothing, just wait the lock screen will cause problems?

I have analyzed and understood why the master password will become invalid. The reason is that the newly added lock screen feature needs to verify the master password. Since WindTerm does not store the master password. Therefore, the validity of the master password is judged by judging whether each encrypted information can be decrypted correctly. In this way, even if the master password is still correct, as long as **any one** of the encrypted information is damaged and cannot be decrypted, the master password verification will be failed. For the user, the master password seems to have been tampered with. 

As in the screenshot above by @huai168an, the abnormal `session.autoLogin` on the right was emptied by mistake, and its empty string caused the decryption to fail. As a result, the master password verification also failed. 

The only thing I can’t understand now is what the encrypted information has been tampered with, an empty string or something else? So please help me compare the `user.session` before and after the error and see what the difference is. thank you very much.

**Comment by Liuhongdan** [comment] 2021-06-25 07:27
@kingToolbox 
Lock screen won't cause the issue.

I got the issue again after 2 days restore from a backup:
![image](https://user-images.githubusercontent.com/17244416/123386366-2c1a5c80-d5c9-11eb-9646-39300bcf0188.png)

![image](https://user-images.githubusercontent.com/17244416/123386767-98955b80-d5c9-11eb-8fe5-705f646bd5d4.png)

**Comment by Liuhongdan** [comment] 2021-06-30 01:54
@kingToolbox 
Thank you for update. Already upgraded to 2.1.0 Prerelease 5. 👍

**Comment by kingToolbox** [comment] 2021-07-17 17:24
It looks like this issue should be fixed, :smile: The latest [WindTerm_2.1.0](https://github.com/kingToolbox/WindTerm/releases/tag/2.1) has just been released, please download and check it. If there is no problem too, the issue will be closed. Thank you all.

**Closed** 2021-07-20 16:37 UTC
Labels: bug

**Comment by ermektaychibekov** [comment] 2022-01-24 13:14
2.2.2 said [that empty] lock passwort incorrect.

but i did not set it!
and i do not know the default!

i saw an option to disable automatic locking (by timeout) at all
but i can't find it now

**Comment by kingToolbox** [comment] 2022-01-25 12:44
@ermektaychibekov

The default `master password` is an empty string. If you can't remember the password, you can open `WindTerm_install_path/profiles/default.v10/user.config` and remove the configuration items `application.fingerprint` and `application.masterPassword`. Note that all automatic login information encrypted with the old master password will be lost.

The `lock screen timeout` setting is in the dialog `MenuBar - Session - Preferences - Settings - Security - Lock screen timeout`,  you can try it.

**Comment by MeKAniml** [comment] 2022-08-17 08:59
hi ! sorry to reopen the issue but on 2.5.0 the master password go back to empty string during my work holiday (the pc may have been shutdown).
I changed it back to a new one but just wanted to prevent you.
