### ISSUE TITLE
希望能够增加登录脚本功能

### ISSUE THREAD

**Issue by cnkmmk** [kingToolbox/WindTerm#328] opened 2021-12-02 02:57 UTC
如同xshell的这个功能
![https://i.imgur.com/TnTInAh.png](https://i.imgur.com/TnTInAh.png)

**Comment by kingToolbox** [comment] 2021-12-03 00:19
Duplicate of #312

Features such as `macros`, `triggers`, `events`, `notifications`, `plugins`, `scripts` and so on will be added in subsequent versions. I will update the progress here, please stay tuned, thank you.

**Closed** 2024-03-09 12:01 UTC
Labels: duplicate
