### ISSUE TITLE
A minor error: When tab is not connected yet, click Close and the entire app will get stuck

### ISSUE THREAD

**Issue by xzhuiz** [kingToolbox/WindTerm#25] opened 2020-11-26 09:56 UTC
When you open a new tab or reopen WindTerm, if a server connection is slow and click Close tab before the connection is complete, the entire app is stuck

**Comment by kingToolbox** [comment] 2020-11-27 12:39
Thank you. It is designed. When the server does not answer or the answer is wrong, WindTerm will try to reconnect to the server 60 times within 30 seconds to make the connection as successful as possible. The whole process is uninterruptible, so closing the tab at this time will cause the interface get stuck.

The next version will try to change it to asynchronous so that the interface can respond quickly. But I am not very sure. I need to evaluate whether this modification is safe.

**Comment by hongnod** [comment] 2021-03-02 15:01
Nice app,
When connect to OpenWRT using ssh with filter pane opened, the whole window will froze.

**Comment by kingToolbox** [comment] 2021-03-02 20:30
Yes, this is a bug and I am fixing it. This is one of the few bugs that needs to be fixed before the final stable version is released. I will release a new version 2.0.0_prerelease_4 soon.

**Comment by hongnod** [comment] 2021-03-03 05:27
thx！

**Comment by kingToolbox** [comment] 2021-03-05 01:57
The fix has been released, please download the new version [2.0.0_prerelease_4](https://github.com/kingToolbox/WindTerm/releases/tag/2.0.0) and check, thank you.

**Comment by hongnod** [comment] 2021-03-05 12:11
Many thanks to you first!
I wrote a wrong word with my last comment. the "filter" should be "filer". 
Test  2.0.0_prerelease_4  to my OpenWrt Router by SSH with only password,  opening two more additional panes: filer and session,  connection to remote  OpenWrt is  fine, the filer pane has nothing in it, then close the openwrt session tab, the application window will frozen.

**Comment by kingToolbox** [comment] 2021-03-06 10:30
Thank you for the detailed description. I have re-fixed and updated the release, please re-download [WindTerm_2.0.0_Prerelease_4_Windows_Portable.zip](https://github.com/kingToolbox/WindTerm/releases/download/2.0.0/WindTerm_2.0.0_Prerelease_4_Windows_Portable.zip) and test again, thank you very much. The Linux version is not updated. If you need Linux version, please let me know and I will make an update.

In addition, I do not have an OpenWrt system, so I am not sure whether the filer panel should be empty or not. If OpenWrt has no corresponding SFTP service, it is recommended to **uncheck** the SFTP service in the session property dialog `Session Property Dialog - SSH - Authentication - When session is authenticated - Enable SFTP`, which can reduce unnecessary connections. But if OpenWrt has SFTP service and you can use other SFTP clients to browse it, it means that there are still bugs, please let me know and I will continue to fix it, thank you.

**Comment by hongnod** [comment] 2021-03-06 16:53
Many thanks to you.
OpenWrt doesn't have SFTP service, unchecking the SFTP service works.
best regards.

**Comment by kingToolbox** [comment] 2021-03-06 19:00
Thank you for the good news. Would you like to do me a favor, please check after **enable (check)**  the `Enable SFTP` option, is everything still works, and will opening and closing the tab still cause WindTerm frozen? Thank you very much.

**Comment by hongnod** [comment] 2021-03-07 00:43
when sftp enable
close filer tab, closing openned session tab without problem, closing window will frozen still

**Comment by kingToolbox** [comment] 2021-03-07 02:21
Will it freeze forever? It is normal if it freezes for ten to fifteen seconds, because it needs to detect whether the remote end is disconnected, but if it exceeds one minute, it will be abnormal. I will continue to work to fix this bug, now you can turn off the SFTP when you use OpenWrt sessions. thank you very much.

**Comment by hongnod** [comment] 2021-03-07 16:12
with sftp.
if click top right "x", no issue.
else close filer->close openned 129 session window(untill this step ok)-> click top right "x"(now window says no reponse as attached png)

![no-response](https://user-images.githubusercontent.com/6680267/110246419-7d62f980-7fa2-11eb-8bcf-df6a4bcae9ed.png)

**Comment by kingToolbox** [comment] 2021-03-07 21:36
Wow, I did not expect to need to close twice. Unfortunately, I still can't reproduce it. However, I rewrote part of the code, and no longer try to open SFTP when it is detected that there is no SFTP support. If this bug is indeed caused by SFTP, I think the problem should be solved.

As last time, I updated the release, please re-download [WindTerm_2.0.0_Prerelease_4_Windows_Portable.zip](https://github.com/kingToolbox/WindTerm/releases/download/2.0.0/WindTerm_2.0.0_Prerelease_4_Windows_Portable.zip) and test. Sorry to trouble you, thank you very much. Sometimes some problems are very annoying. :persevere:

**Comment by hongnod** [comment] 2021-03-08 13:38
You are so kind and have patience. thanks!
the bad news is that problem is still existed. but I'd like you not  spend time on this. It can be avoided by unchecking "SFTP", so it's not a big deal. the application is great so as is enough.
thanks and best regards.

**Comment by hongnod** [comment] 2021-03-08 13:42
You are so kind and have patience. thanks!
the bad news is that problem is still existed. but I'd like you not  spend time on this. It can be avoided by unchecking "SFTP", so it's not a big deal. the application is great so as is enough.
thanks and best regards.

**Comment by kingToolbox** [comment] 2021-03-11 23:20
Thank you too! The stable version [v2.0.0](https://github.com/kingToolbox/WindTerm/releases/tag/2.0) has been released, please download and use it.

This issue will be closed but the problem will still be investigated and fixed. I will try to install OpenWRT again in the virtual machine to reproduce the problem. In fact, I tried to install it twice before asking for help, but failed. I can only trouble you. I am very grateful for your patience and suggestions. :+1:

**Closed by kingToolbox** 2021-03-11 23:20 UTC
Labels: bug

**Comment by Ansen** [comment] 2023-12-18 09:19
> Thank you. It is designed. When the server does not answer or the answer is wrong, WindTerm will try to reconnect to the server 60 times within 30 seconds to make the connection as successful as possible. The whole process is uninterruptible, so closing the tab at this time will cause the interface get stuck.
> 
> The next version will try to change it to asynchronous so that the interface can respond quickly. But I am not very sure. I need to evaluate whether this modification is safe.

How to turn off reconnection? or reduce its frequency

Current Version: 2.6.0 Pre 2
