### ISSUE TITLE
group name disappeared in Quick Commands

### ISSUE THREAD

**Issue by JamesRupy** [kingToolbox/WindTerm#166] opened 2021-08-18 08:23 UTC
After I  added group in **Quick Commands**,then clicked **rename group**,then "Cancel",this group name will disappeared,the content in `profiles\default.v10\terminal\quickbar.config` will like:

```json
[
    {
        "quick.icon" : "session::knot-forestgreen",
        "quick.label" : "start",
        "quick.text" : "start\n",
        "quick.type" : "Send Text",
        "quick.uuid" : "111-44ab-4491-b07c-111"
    },
    {
        "quick.icon" : "session::knot-forestgreen",
        "quick.label" : "stop",
        "quick.text" : "stop\n",
        "quick.type" : "Send Text",
        "quick.uuid" : "222-8bca-4175-acbc-222"
    },
    {
        "quick.group" : "Quick",
        "quick.icon" : "session::square-forestgreen",
        "quick.label" : "activate",
        "quick.text" : "activate\n",
        "quick.type" : "Send Text",
        "quick.uuid" : "333-3ffd-4c34-990b-333"
    }
]
```

The issue is "start" and "stop" items don't have the **quick.group** attribute.So I can not modify them.

If I add **"quick.group" : "AAA",** to  "start" and "stop",then restart WindTerm,the new group(AAA) and items will be available

If there are two groups or more,check the group name when saving config will better.

**Comment by kingToolbox** [comment] 2021-08-18 19:12
Thank you for providing such a detailed description. This bug has been confirmed and will be fixed in the next version. If there is progress, I will update it here.

**Comment by kingToolbox** [comment] 2021-09-26 05:53
Sorry for the late reply. I just finished a long trip, and because there is no Internet, I can't deal with the issue in time. 

I am happy to inform you that [WindTerm_2.2.0_Prerelease_1](https://github.com/kingToolbox/WindTerm/releases/tag/2.2-prerelease) has been released and this issue has been fixed. You can download and check it now. Thank you.

**Closed** 2021-10-10 03:26 UTC
Labels: bug
