### ISSUE TITLE
the delay of keyboard input

### ISSUE THREAD

**Issue by leesings** [kingToolbox/WindTerm#167] opened 2021-08-19 05:57 UTC
![image](https://user-images.githubusercontent.com/43227866/130015295-499e5b16-fb0b-43e5-bd8d-b3705830c25f.png)

When uploading files, the delay of keyboard input becomes higher. After uploading, it returns to normal .

**Comment by kingToolbox** [comment] 2021-08-19 19:42
This is possible. Because the `libssh` library dose not support using a single session in serveral threads, so the file transfer channel and the shell channel share the same thread and socket. When inputting a command, if it happens to be transmitting a data block of the file, the command must wait for the current data block to be sent and confirmed before it will be sent and executed. In addition, reading and writing the disks, such as server-side reading files from disk and client-side writing files to disk, will also cause a certain delay. 

The performance of the server and client, the performance of the network, the transmission speed, and the speed of reading and writing the disks may all affect the input delay. For example, in my test environment, because it is a local network, no delay is felt when inputting commands when transferring large files or multiple files. 

If you need to transmit a large amount of data, it is recommended to open a new session to transmit, so that there will be two threads to process the transmission and the command separately, which should be able to avoid input delay. Of course, this still depends on the processing performance of the server. 

In addition, the time to transfer files is usually very short,so it will not have too much negative impact on the command input experience.

**Comment by onlyGuo** [comment] 2021-08-21 06:31
I think this is normal, and any ssh terminal has this problem.

**Comment by leesings** [comment] 2021-08-24 01:29
Thank you for your reply

**Comment by kingToolbox** [comment] 2021-09-26 22:03
Ok, I think this issue has been resolved and will be closed. Thank you.

**Closed by kingToolbox** 2021-09-26 22:03 UTC
