### ISSUE TITLE
Cmd doesn't start normally when WindTerm is installed in path with spaces

### ISSUE THREAD

**Issue by githublife** [kingToolbox/WindTerm#746] opened 2022-05-11 02:09 UTC
![放在了一个带空格的目录下面](https://user-images.githubusercontent.com/13509023/167754643-816a4635-ea1c-46f2-88f8-2db37cba5d4c.png)

**Comment by kingToolbox** [comment] 2022-05-19 00:34
Duplicate of #736 

Sorry for the late reply, because I have some personal matters to take care of recently.

I am happy to inform you that [WindTerm_2.5.0_Prerelease_1](https://github.com/kingToolbox/WindTerm/releases/tag/2.5-prerelease) has been released and this bug has been fixed. Please download and check it, thank you.

**Closed** 2022-05-23 08:37 UTC
Labels: duplicate
