### ISSUE TITLE
Session 能否保存,并支持批量导入导出

### ISSUE THREAD

**Issue by sjditadmin** [kingToolbox/WindTerm#164] opened 2021-08-18 02:34 UTC
Session 能否保存,并支持批量导入导出
现在的session save后不能保存用户密码信息

**Comment by kingToolbox** [comment] 2021-08-18 04:02
Duplicate of  #161 

WindTerm supports batch import of sessions of OpenSSH and PuTTY by default, and the `profiles\default.v10\terminal\user.sessions` configuration file is in the json format, so you can export it yourself. You can read [this comment](https://github.com/kingToolbox/WindTerm/issues/161#issuecomment-900085446) for a more detailed description. 

Login information, including user name and password, can be saved only when logging in. You can watch [Auto Login](https://kingtoolbox.github.io/2020/01/23/auto-login/) to learn more. This video is based on the old version, but the usage is almost the same.

**Comment by kingToolbox** [comment] 2021-09-26 21:39
This issue has been resolved and will be closed. Thank you.

**Closed** 2021-09-26 21:39 UTC
Labels: duplicate
