### ISSUE TITLE
Would you support copy on select and right click paste ?

### ISSUE THREAD

**Issue by Liuhongdan** [kingToolbox/WindTerm#58] opened 2021-03-11 02:40 UTC
Hi, I'm using WindTerm. It's fast and uses less memory than others, and also has a lot of features.
I know that the shortcuts for  copy and paste, but could you support copy on select and right click paste ? It will make it more convenient to daily use.
It will be better if you can support Iterm Themes (https://iterm2colorschemes.com/). So people can just download/use the color schemes that they want.
And pls support auto upgrade :)

Thank you.

**Comment by kingToolbox** [comment] 2021-03-12 00:43
Duplicate of #19.

Copy on select is already supported, and I think drag and drop the selection to input it is more 
convenient to use. You can read the description [here](https://github.com/kingToolbox/WindTerm/issues/19#issuecomment-719334753).

However, only the middle mouse button is supported for pasting at present, and the right button is more suitable for pop-up menus. But if you really want to use the right button to paste. Then you need to wait for the completion of the keyboard and mouse customization, which is expected in the third quarter.

WindTerm's themes is more complicated than Iterm and more closer to vscode. You can customize your theme based on `windterm-install-path/global/themes/dige-black/scheme.theme`. But I’m afraid WindTerm cannot use Iterm's themes directly. I will write a document on how to customize the theme in the future, so that more themes could be created and shared for you to choose from.

Auto upgrade is not considered for the time being. This is not for technical reasons. But auto upgrade requires regular and spontaneous access to the external network, and security is very sensitive to ssh clients. Before WindTerm gains universal acceptance, spontaneous access to the Internet will bring unnecessary suspicion.

**Comment by Liuhongdan** [comment] 2021-03-12 03:26
Just set the option text.autoCopySelection in WindTerm-Install-Path/global/wind.config to true to enable it.  Select-to-copy and middle-click-to-paste and drag and drop are easy to use. Need this select-to-copy, because sometimes need to copy from WindTerm to other applications. For right button to paste, I'm ok to wait since middle-click-to-paste is already there. I think this setting better can be merge into WindTerm setting in UI in the future, otherwise it's hard for others to know.
I will try scheme.theme later.

BTW, for upgrade, if I download a new version, should I extract it to current WindTerm folder, or can it export current sessions into new version ?

Thank you. 👍

**Comment by kingToolbox** [comment] 2021-03-12 05:05
WindTerm supports drag and drop between programs. You can read [Tips / Input By Dragging And Dropping Text](https://kingtoolbox.github.io/2020/06/20/tips-input-by-dragging-and-dropping-text/) to known more. Of course, it is more convenient to copy and paste between programs. Windows doesn't have the concept of a separate selection and clipboard like X11 Window System, so I set the default value of the option `text.autoCopySelection` to false.

The settings will definitely have an interface, but the priority of development is relatively low. I look forward to completing it gradually in the new 2.x series. 

The upgrade of WindTerm is very simple, as I stated in the release:

`Copy or move the "profiles" folder from the old Windows/Linux version to the new Windows/Linux version and all the sessions and configuration will be restored.`

The new [v2.0.0](https://github.com/kingToolbox/WindTerm/releases/tag/2.0) stable version has just been released, you can download and use it. Thank you.

**Comment by Liuhongdan** [comment] 2021-03-12 10:08
Just downloaded and copied "profiles" to v2.0.0.
Thank you!

**Comment by kingToolbox** [comment] 2021-05-27 22:11
The configuration GUI will be completed in the next version 2.2.0. Welcome to continue submitting new issues and feature requests, thank you.

**Closed by kingToolbox** 2021-05-27 22:11 UTC
Labels: duplicate

**Comment by kingToolbox** [comment] 2021-07-07 06:21
Hello, the `right-click-to-paste` feature has been supported. Please download and use [WindTerm_2.1.0_Prerelease_6_Windows_Portable](https://github.com/kingToolbox/WindTerm/releases/tag/2.1-prerelease). 

After downloading it, set **terminal.rightClickAction** in `WindTerm_install_path/profiles/default.v10/user.config` or `WindTerm_install_path/global/wind.config` to **PasteText** to enable it. At the same time, it is best to set **text.autoCopySelection** to `true.` It is more convenient to use **terminal.rightClickAction** and **text.autoCopySelection** together.

**Comment by xihajun** [comment] 2023-02-17 16:26
may I ask any idea where can we find the wind.config tempalte

**Comment by baternest** [comment] 2023-10-11 03:14
Session > Preferences > Settings... > Text
Check the option "Automatically copy selection" 
![image](https://github.com/kingToolbox/WindTerm/assets/1662113/839f95b9-5f12-4dcd-8fac-d267e2869614)

**Comment by todaygood** [comment] 2024-12-24 10:32
I found  it couldn't copy selected text to clipboard  under windterm the latest linux portable  version in Deepin Linux 20.
