### ISSUE TITLE
Text gets separated when two monitors have different scale and layout

### ISSUE THREAD

**Issue by Liuhongdan** [kingToolbox/WindTerm#73] opened 2021-04-05 04:47 UTC
1st screenshot is from a laptop, with scale and layout value 150:
![image](https://user-images.githubusercontent.com/17244416/113537991-ae1f6880-960c-11eb-96b4-5cc02b59b168.png)

2nd screenshot is from a monitor connects to the laptop, with scale and layout value 100:
![image](https://user-images.githubusercontent.com/17244416/113538013-c1323880-960c-11eb-8b84-7a9ba8d5f294.png)

If I change the monitor to use the same value, then the text is back to normal.
Any suggestions for this ? Others applications are OK.

**Comment by kingToolbox** [comment] 2021-04-05 06:35
Thank you. This is obviously a bug, and I will fix this in version 2.1.0.

BTW, Is this a Windows system? Do icons, buttons, or other window widgets and text on the widgets look normal?

**Comment by Liuhongdan** [comment] 2021-04-06 01:48
Yes. It's Windows 10 HOME.
Just checked. Icons, buttons and other window widgets and text on the widgets look normal.

**Comment by kingToolbox** [comment] 2021-04-07 13:30
Thank you, if everything else is displayed normally, then it should be a problem with the text view itself. I am already reproducing and fixing the bug, and I hope to fix it as soon as possible.

**Comment by kingToolbox** [comment] 2021-05-27 22:25
Sorry to keep you waiting. [WindTerm_2.1.0_Prerelease_3](https://github.com/kingToolbox/WindTerm/releases/tag/2.1) has just been released and this issue has been fixed. You can download and check it now. Thank you.

**Comment by gooker** [comment] 2021-05-28 00:32
> Sorry to keep you waiting. [WindTerm_2.1.0_Prerelease_3](https://github.com/kingToolbox/WindTerm/releases/tag/2.1) has just been released and this issue has been fixed. You can download and check it now. Thank you.

p3  also have this issue,

laptop 150% dpi,  monitor 100% dpi, in monitor :
<img width="683" alt="20210528083224" src="https://user-images.githubusercontent.com/5688076/119912987-40017d00-bf8f-11eb-8754-0063181ecb25.png">

**Comment by kingToolbox** [comment] 2021-05-28 00:45
A little disappointed. I will check and refix this, thank you very much.

**Comment by kingToolbox** [comment] 2021-05-28 00:50
You can start two WindTerms in the two screens now to circumvent this problem. It should be similar to the two windows of one WindTerm.

**Comment by gooker** [comment] 2021-06-05 02:26
> You can start two WindTerms in the two screens now to circumvent this problem. It should be similar to the two windows of one WindTerm.

I found a way, in the abnormal display window, enter the menu->view->zoom,zoom in/out  will return to normal display

But I've changed the monitor(same DPI as my laptop)...

**Comment by kingToolbox** [comment] 2021-06-15 21:13
Thank you. I should have fixed the bug that the current screen resolution changes caused the display to be abnormal. But since the computer I am using does not have a second monitor, I cannot test the scenario with two monitors. Fortunately, I will have the opportunity to test the dual-monitor scenario next month. By then I think I should be able to complete the fix of this issue. :smile:

**Comment by kingToolbox** [comment] 2021-06-28 07:40
Hello, I tried to fix the problem again. There is a defect in the previous fix that will cause WindTerm to fail to respond to the change of the the monitors. But I still don't have dual-monitors for testing. So I am not sure if it is really fixed. If not, I will wait until the dual-monitors becomes available next month and try to fix it again. 

You can download [WindTerm_2.1.0_Prerelease_5](https://github.com/kingToolbox/WindTerm/releases/tag/2.1-prerelease) and check it now, thank you.

**Comment by kingToolbox** [comment] 2021-06-28 07:40
Hello, I tried to fix the problem again. There is a defect in the previous fix that will cause WindTerm to fail to respond to the change of the the monitors. But I still don't have dual-monitors for testing. So I am not sure if it is really fixed. If not, I will wait until the dual-monitors becomes available next month and try to fix it again. 

You can download [WindTerm_2.1.0_Prerelease_5](https://github.com/kingToolbox/WindTerm/releases/tag/2.1-prerelease) and check it now, thank you.

**Comment by kingToolbox** [comment] 2021-06-28 07:41
Hello, I have tried to fix the problem again. There is a defect in the previous fix that will cause WindTerm to fail to respond to the change of the the monitors. But I still don't have dual-monitors for testing. So I am not sure if it is really fixed. If not, I will wait until the dual-monitors becomes available next month and try to fix it again. 

You can download [WindTerm_2.1.0_Prerelease_5](https://github.com/kingToolbox/WindTerm/releases/tag/2.1-prerelease) and check it now, thank you.

**Comment by kingToolbox** [comment] 2021-07-17 17:05
Hello, [WindTerm_2.1.0](https://github.com/kingToolbox/WindTerm/releases/tag/2.1) has just been released and this issue has been finally fixed, please download and check it, thank you.

**Comment by kingToolbox** [comment] 2021-07-20 16:36
The issue should have been fixed in the new [WindTerm_2.1.0](https://github.com/kingToolbox/WindTerm/releases/tag/2.1) and self-test passed. Please reopen this issue if it is still valid. Thank you.

**Closed by kingToolbox** 2021-07-20 16:36 UTC
Labels: bug
