### ISSUE TITLE
软件无法切换输入法输入中文，大家有没有遇到过这个问题？

### ISSUE THREAD

**Issue by ruansoft08** [kingToolbox/WindTerm#203] opened 2021-09-25 12:03 UTC

**Comment by yaronzz** [comment] 2021-09-26 01:35
没有

**Comment by littlecong** [comment] 2021-09-26 04:05
没有

**Comment by kingToolbox** [comment] 2021-09-26 04:54
There are currently two known issues, #39 and #125, both of which describe that the Linux IMEs based on fcitx cannot input Chinese. These issues have been fixed and will be released as version 2.2.0 Prerelease 3 or 2.2.0 Prerelease 4. 

If you feel that the problem is not like yours, please describe your operating system version, WindTerm version, and input method name and version to facilitate the reproduction of the problem. Thank you.

**Comment by kingToolbox** [comment] 2021-11-06 22:48
The new [WindTerm_2.2.0_Prerelease_4](https://github.com/kingToolbox/WindTerm/releases/tag/2.2-prerelease) version has been released and this issue may has been fixed, please download and check it. If this problem persists, please let me know and I will continue to fix it, thank you.

**Comment by ruansoft08** [comment] 2021-11-07 06:58
I have tried the new version, the problem of Chinese input method has been solved. Thank you！


---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年11月7日(周日) 上午6:48
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [kingToolbox/WindTerm] 软件无法切换输入法输入中文，大家有没有遇到过这个问题？ (#203)




 
The new WindTerm_2.2.0_Prerelease_4 version has been released and this issue may has been fixed, please download and check it. If this problem persists, please let me know and I will continue to fix it, thank you.
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by kingToolbox** [comment] 2021-11-07 07:59
Ok, this issue will be closed, and welcome to submit new feature requests and bugs, thank you.

**Closed by kingToolbox** 2021-11-07 07:59 UTC
