### ISSUE TITLE
Hope to add simplified Chinese UI

### ISSUE THREAD

**Issue by onlyGuo** [kingToolbox/WindTerm#168] opened 2021-08-20 00:56 UTC
Hope to add simplified Chinese UI, thank you! 
My Email: 719348277@qq.com

**Comment by huai168an** [comment] 2021-08-20 01:55
作者后期会加入翻译的，都提了很久了，哈哈哈，作者现在主要在关注功能问题，稳定了就考虑翻译问题了，看样子还是国内用户比较多啊

**Comment by onlyGuo** [comment] 2021-08-20 02:15
> 作者后期会加入翻译的，都提了很久了，哈哈哈，作者现在主要在关注功能问题，稳定了就考虑翻译问题了，看样子还是国内用户比较多啊

UI不急，但中文崩溃问题应优先解决呀，创建session时如果输入中文，后续操作会引发崩溃，windows10系统

**Comment by kingToolbox** [comment] 2021-08-20 04:35
Duplicate of #6 #22 #43 #88

I will provide localized languages in the next stable `WindTerm_2.2.0` version. I have been working hard to develop the `Master Control` feature since this month. Due to the limitations of the old design, it is necessary to refactor almost all the core code to complete this feature, which leads to heavy development and testing tasks. Many features and bug fixes have been delayed.

At present, the refactoring of more than 10,000 lines of code and the `Master Control` feature has been completed, and testing is underway to ensure that all existing functions are still normal. The next step is to quickly fix the crash on the MacOS system and release the bugfix version, and then the next step is to provide the localized languages, I hope it can be completed sooner.

**Comment by hongnod** [comment] 2021-08-20 06:07
这种软件，中文很有必要吗？

**Comment by onlyGuo** [comment] 2021-08-21 06:26
> 这种软件，中文很有必要吗？

我并没有在意中文，这个问题是我用了一段时间以后推荐给同事时暴露的问题，同事问我在哪里设置语言时我才发现找不到设置入口。
也许每个人的使用习惯不太一样。所以我觉得可能大多数用它的人不会关心语言，但软件本身应该支持第三方语言。
我也希望作者将功能和稳定性放到首位来对待，当有额外的精力时再去完善界面语言。
这是一个了不起的软件。

**Comment by kingToolbox** [comment] 2021-11-06 22:58
The new [WindTerm_2.2.0_Prerelease_4](https://github.com/kingToolbox/WindTerm/releases/tag/2.2-prerelease) version has been released and the Chinese interface has been supported, please download and check it, thank you.

**Closed** 2021-12-06 07:03 UTC
Labels: duplicate
