### ISSUE TITLE
The new version of the terminal font has become a bit strange and much more compact, which is not very suitable

### ISSUE THREAD

**Issue by iujoker** [kingToolbox/WindTerm#1957] opened 2023-11-21 02:07 UTC
After experiencing the new version of [WindTerm_2.6.0_Prerelease_4], I feel that the font on the terminal has become much more compact, and the highlighted font will be larger than the regular one, which is not very suitable. It's better to use the old version again

**Comment by kingToolbox** [comment] 2023-12-02 08:32
Duplicate of #1950

**Closed by kingToolbox** 2023-12-02 08:32 UTC
Labels: duplicate
