### ISSUE TITLE
Hyperlink not supported

### ISSUE THREAD

**Issue by skbeh** [kingToolbox/WindTerm#453] opened 2022-01-14 17:07 UTC
The output of `ls -a --hyperlink`  in WindTerm:
```
~ ❯ mkdir dir
~ ❯ cd dir
~/dir ❯ ls -a --hyperlink
]8;;file://hostname/home/username/dir]8;;]8;;file://hostname/home/username]8;;.  ..
```

The output in Windows Terminal:
```
~ ❯ cd dir
~/dir ❯ ls -a --hyperlink
.  ..
```

**Comment by kingToolbox** [comment] 2022-01-19 06:22
Duplicate of #160

`OSC 8` will be supported in the next `WindTerm 2.4` version, which expected to be released in February. Please stay tuned, thank you.

**Comment by kingToolbox** [comment] 2022-01-28 06:58
I am happy to inform you that [WindTerm_2.3.0_Prerelease_3](https://github.com/kingToolbox/WindTerm/releases/tag/2.3-prerelease) has been released and this issue has been fixed, please download and check it, thank you.

**Closed** 2022-08-07 14:54 UTC
